version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/college_db
    ports:
      - 8080:8080
    restart: on-failure

volumes:
  mongo-data:
    driver: local
