app:
  console:
    enabled: false

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/college_db}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
